- README.md
> Fixes README.md Link

- src/HttpFunctionWrapper.php
- tests/HttpFunctionWrapperTest.php
> Adjust path handling for robots.txt and favicon.ico

- composer.json
- router.php
- src/BackgroundFunctionWrapper.php
- src/Emitter.php
- src/FunctionWrapper.php
- src/HttpFunctionWrapper.php
- src/Invoker.php
- tests/BackgroundFunctionWrapperTest.php
- tests/EmitterTest.php
- tests/HttpFunctionWrapperTest.php
- tests/InvokerTest.php
- tests/routerTest.php
> feat: uses guzzle/psr and psr-7 instead of http-foundation

- .travis.yml
- README.md
- examples/hello/composer.json
- examples/hello/index.php
- tests/exampleTest.php
Updates docs for PSR-7 and adds better testing so this doesn't happen again!
> docs: updates examples for PSR-7, adds example test

- src/BackgroundFunctionWrapper.php
- tests/BackgroundFunctionWrapperTest.php
> feat: throw better exception for empty request body

- src/BackgroundFunctionWrapper.php
- tests/BackgroundFunctionWrapperTest.php
> feat: allows context property to be omitted for background functions

- composer.json
> docs: specify minimum version of PHP in composer.json

- README.md
- src/FunctionWrapper.php
- tests/CloudEventFunctionsWrapperTest.php
- tests/HttpFunctionWrapperTest.php
- tests/exampleTest.php
- tests/fixtures/absolute.php
- tests/fixtures/index.php
- tests/fixtures/relative.php
- tests/vendorTest.php
- Better exceptions for function validation
- fixes tests 
- updates README
- removes `TRAVIS` env vars
> fix: tests, exceptions and readme

- src/CloudEventFunctionWrapper.php
- tests/CloudEventFunctionsWrapperTest.php
- tests/fixtures/composer.json
fixes https://github.com/GoogleCloudPlatform/functions-framework-php/issues/58
> feat: add support for structured events

- README.md
- examples/hello/Dockerfile
Updated example Dockerfile and related documentation to PHP 7.4
> chore: update example and documentation to PHP 7.4

- README.md
The functions framework is ready for production use.
> Remove disclaimer about production use from the README

- src/FunctionWrapper.php
Avoid recurring calls to `count()`, especially do call it within a loop
This can safely be extracted into a variable
> Avoid recurring calls to count().

- .php_cs.dist
- README.md
This PR fixes 2 depreciations.
> Fix depreciations

- router.php
- src/ProjectContext.php
- tests/ProjectContextTest.php
Adds the class `ProjectContext`, which has the following features:
1. Locates the `autoload.php` file (if it exists)
1. Locates the function source (if it exists)
> chore: refactor router into helper class

- src/ProjectContext.php
> chore: minor cleanup in ProjectContext

- .php_cs.dist.php
- src/LegacyEventMapper.php
> Add PHP71Migration ruleset

- .github/workflows/conformance.yml
- .github/workflows/unit.yaml
The current version of PHP is 8, that would be a pity not to test it.
> Add tests for PHP 8.

- src/HttpFunctionWrapper.php
- src/Invoker.php
- src/LegacyEventMapper.php
- tests/InvokerTest.php
- tests/LegacyEventMapperTest.php
Remain consistant and prefer import over FQCN.
> Remain consistant and prefer import over FQCN.

- tests/CloudEventFunctionsWrapperTest.php
- tests/CloudEventTest.php
- tests/ContextTest.php
- tests/EmitterTest.php
- tests/HttpFunctionWrapperTest.php
- tests/InvokerTest.php
- tests/LegacyEventMapperTest.php
- tests/ProjectContextTest.php
- tests/routerTest.php
- tests/vendorTest.php
Hint the return type for all `/tests` functions.
> Hint the return type for all tests functions.

- tests/ProjectContextTest.php
> Use dedicated test assertion.

- src/CloudEventFunctionWrapper.php
- src/LegacyEventMapper.php
- tests/LegacyEventMapperTest.php
Adds ability to detect messages from the PubSub emulator,
and properly convert them to CloudEvent events.
> fix: Fix local dev with PubSub emulator

- CONTRIBUTING.md
Fixes https://github.com/GoogleCloudPlatform/functions-framework-php/issues/108
Hey Brent,
This PR adds note about how to release this library. (We're trying to do this across languages)
Please make any suggestions in alternative wording, or feel free to create a separate PR to address this issue.
> Update CONTRIBUTING.md with Releasing Process

- src/FunctionsFrameworkTesting.php
- tests/FunctionsFrameworkTest.php
> feat: add class for testing

- .github/workflows/conformance.yml
- .github/workflows/unit.yaml
ci: Add 8.1 to versions to be tested
> ci: Add 8.1 to versions to be tested

- composer.json
- tests/FunctionsFrameworkTest.php
- tests/InvokerTest.php
- tests/TypedFunctionWrapperTest.php
follow up to review comments in https://github.com/GoogleCloudPlatform/functions-framework-php/pull/141 which were not addressed
> chore: refactor includes in favor of autoload-dev

- .github/workflows/conformance.yml
- tests/conformance/index.php
- tests/conformance/run_conformance_tests.sh
Adds conformance testing of the typed function signature.
> chore: add conformance test coverage for typed function signature

- .github/blunderbuss.yml
Noticed we only have one maintainer in the auto assigner list, adding myself to lessen the burden.
> chore: self to functions-framework-php autoassigner

- tests/InvokerTest.php
fix phpunit error introduced by 11.3 dependency (provider must be static)
> chore: fix CI
